### PR TITLE
Sollongqua master

### PR DESCRIPTION
**Pull request by Zyta-Zurawska**
Migrated #1 by @sollongqua to an actual branch to make it easier on us all.

This is about the sidebar and the actual `infowindow` and `pell` playing nicely together for new markers/form.

### CODE REVIEW

**Comment by Zyta-Zurawska** [comment]
Currently the new form is ineffectual AFAIK; it doesn't actually submit new data/new markers. This can be easily fixed. I haven't tested though; as my latest commit in this PR reads, I was merely appeased by getting Pell to work inside the new marker form infowindow.

**Comment by Zyta-Zurawska** [comment]
Looks good! I'll take things form here!

**Comment by sollongqua** [comment]
-Added some metadata to markers 
-Removed some of pell features and added erase html-tag button 
-Replaced googles icons with temporary icons (only truk,ak,skull icons will work)

**Comment by Zyta-Zurawska** [comment]
This new commit broke making things bold, italic, etc...

**Comment by Zyta-Zurawska** [comment]
Hey there, @sollongqua, I made a nice, big commit that fixes and implements various things! I would love and appreciate it if you were to just take a look over and tell me what you think. Do you think anything else needs to be done before merging this PR/branch to master and cutting a v0.1.0 release?

**Pull request merged**
